/**
 * Default location of the e-mail header logo: the official Rotaract
 * Distrito 4845 lockup, 400×141 PNG shown at 200 px (2x), served by
 * mirotaract-web from public/brand (generated by
 * packages/design-tokens/scripts/build-brand.mjs). It must be an absolute
 * https URL: mail clients fetch it from outside.
 */
export const DEFAULT_EMAIL_LOGO_URL =
  "https://app.rotaract4845.com/brand/logo-rotaract-distrito-4845.png";

function escapeAttribute(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/"/g, "&quot;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
}

/**
 * Wraps the body of a transactional e-mail in the shared layout: the logo
 * on top, then the message. Table-based with inline styles, the only layout
 * every mail client renders the same.
 */
export function emailLayout(
  bodyHtml: string,
  logoUrl: string = process.env.KERNEL_EMAIL_LOGO_URL || DEFAULT_EMAIL_LOGO_URL,
): string {
  return [
    '<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="background:#ffffff">',
    '<tr><td align="center" style="padding:24px 16px">',
    '<table role="presentation" width="100%" cellpadding="0" cellspacing="0" border="0" style="max-width:560px">',
    `<tr><td style="padding:0 0 24px 0;border-bottom:1px solid #eeeeee"><img src="${escapeAttribute(logoUrl)}" width="200" height="71" alt="Rotaract Distrito 4845" style="display:block;border:0;width:200px;height:auto"></td></tr>`,
    `<tr><td style="padding:24px 0 0 0;font-family:Arial,Helvetica,sans-serif;font-size:15px;line-height:1.5;color:#1f2328">${bodyHtml}</td></tr>`,
    "</table>",
    "</td></tr>",
    "</table>",
  ].join("\n");
}
