/**
 * E7 — public event catalog. THE source of truth for:
 *
 * - what `GET /events/catalog` serves (types, descriptions, required scope,
 *   JSON Schema of `data`, a full example of the POSTed body);
 * - which types an endpoint may subscribe to (WebhooksService);
 * - docs/developers/catalogo-de-eventos.md (generated by
 *   `scripts/generate-events-catalog.mjs`, checked by catalog.spec.ts).
 *
 * Public names are stable and versioned per type (`.v1`). A breaking change
 * to `data` is a new type (`.v2`) published next to the old one for a while,
 * never an edit of an existing schema. Adding an optional field is not
 * breaking.
 *
 * The `data` views reuse the Data API v1 projections (views.ts), with the
 * same PII rules: contact fields only with
 * `kernel.service.persons.contact.read`, never internal notes.
 */

export type JsonSchema = Record<string, unknown>;

export type EventDefinition = {
  /** Public type, e.g. "membership.activated.v1". */
  type: string;
  /** Type without its version, e.g. "membership.activated". */
  name: string;
  version: number;
  /** Short Spanish label for the console. */
  title: string;
  /** Spanish description: when it happens. */
  description: string;
  /** Service scope the app needs to receive it (null: every app). */
  scope: string | null;
  /** JSON Schema (draft 2020-12) of `data`. */
  schema: JsonSchema;
  /** Example of `data`. */
  example: Record<string, unknown>;
};

const nullableString = { type: ["string", "null"] };
const nullableDateTime = { type: ["string", "null"], format: "date-time" };

const MEMBERSHIP_STATUS = [
  "PENDING",
  "ACTIVE",
  "ON_LEAVE",
  "INACTIVE",
  "GRADUATED",
  "TRANSFERRED",
];

export const PERSON_VIEW_SCHEMA: JsonSchema = {
  type: "object",
  description:
    "Igual que PersonView de la API de datos. email, phone y birthDate solo aparecen si la app tiene kernel.service.persons.contact.read.",
  required: ["id", "displayName", "firstName", "lastName", "updatedAt"],
  properties: {
    id: { type: "string" },
    displayName: { type: "string" },
    firstName: { type: "string" },
    lastName: { type: "string" },
    avatarUrl: nullableString,
    email: nullableString,
    phone: nullableString,
    birthDate: { type: ["string", "null"], format: "date" },
    updatedAt: { type: "string", format: "date-time" },
  },
};

export const MEMBER_VIEW_SCHEMA: JsonSchema = {
  type: "object",
  description: "Igual que MemberView de la API de datos.",
  required: [
    "membershipId",
    "organizationId",
    "personId",
    "status",
    "person",
    "updatedAt",
  ],
  properties: {
    membershipId: { type: "string" },
    organizationId: { type: "string" },
    personId: { type: "string" },
    status: { type: "string", enum: MEMBERSHIP_STATUS },
    joinedAt: nullableDateTime,
    memberNumber: nullableString,
    person: PERSON_VIEW_SCHEMA,
    updatedAt: { type: "string", format: "date-time" },
  },
};

export const AUTHORITY_VIEW_SCHEMA: JsonSchema = {
  type: "object",
  description: "Igual que AuthorityView de la API de datos (sin contacto).",
  required: [
    "appointmentId",
    "organizationId",
    "periodId",
    "positionCode",
    "positionName",
    "status",
    "person",
  ],
  properties: {
    appointmentId: { type: "string" },
    organizationId: { type: "string" },
    periodId: { type: "string" },
    positionCode: { type: "string" },
    positionName: { type: "string" },
    status: {
      type: "string",
      enum: ["NOMINATED", "ELECTED", "ACTIVE", "ENDED", "REVOKED"],
    },
    startsAt: nullableDateTime,
    endsAt: nullableDateTime,
    person: {
      type: "object",
      required: ["id", "displayName"],
      properties: {
        id: { type: "string" },
        displayName: { type: "string" },
        avatarUrl: nullableString,
      },
    },
  },
};

export const ORGANIZATION_VIEW_SCHEMA: JsonSchema = {
  type: "object",
  description: "Igual que OrganizationView de la API de datos.",
  required: ["id", "type", "code", "name", "slug", "status", "updatedAt"],
  properties: {
    id: { type: "string" },
    type: { type: "string", enum: ["DISTRICT", "CLUB", "OTHER"] },
    code: { type: "string" },
    name: { type: "string" },
    slug: { type: "string" },
    status: {
      type: "string",
      enum: ["DRAFT", "ACTIVE", "INACTIVE", "ARCHIVED"],
    },
    parentId: nullableString,
    countryCode: nullableString,
    region: nullableString,
    city: nullableString,
    timezone: nullableString,
    logoUrl: nullableString,
    description: nullableString,
    updatedAt: { type: "string", format: "date-time" },
  },
};

export const PERIOD_VIEW_SCHEMA: JsonSchema = {
  type: "object",
  description: "Igual que PeriodView de la API de datos.",
  required: [
    "id",
    "organizationId",
    "code",
    "name",
    "status",
    "startDate",
    "endDate",
  ],
  properties: {
    id: { type: "string" },
    organizationId: { type: "string" },
    code: { type: "string" },
    name: { type: "string" },
    status: {
      type: "string",
      enum: ["DRAFT", "SCHEDULED", "ACTIVE", "CLOSED", "CANCELLED"],
    },
    startDate: { type: "string", format: "date-time" },
    endDate: { type: "string", format: "date-time" },
  },
};

const changedFields = {
  type: "array",
  items: { type: "string" },
  description:
    "Nombres de los campos que cambiaron (no sus valores anteriores). Puede venir vacío en eventos registrados antes de que el kernel los informara.",
};

const ORG = "cm1clubsanlorenzo0000000";
const PERSON = "cm1personanaperez0000000";
const MEMBERSHIP = "cm1membershipanaperez000";
const updatedAt = "2026-10-02T21:15:04.000Z";
const examplePerson = {
  id: PERSON,
  displayName: "Ana Pérez",
  firstName: "Ana",
  lastName: "Pérez",
  avatarUrl: null,
  updatedAt,
};
const exampleMember = (status: string, joinedAt: string | null) => ({
  membershipId: MEMBERSHIP,
  organizationId: ORG,
  personId: PERSON,
  status,
  joinedAt,
  memberNumber: "1042",
  person: examplePerson,
  updatedAt,
});
const exampleAuthority = (status: string) => ({
  appointmentId: "cm1appointmentanaperez00",
  organizationId: ORG,
  periodId: "cm1period2026club0000000",
  positionCode: "CLUB_PRESIDENT",
  positionName: "Presidente/a",
  status,
  startsAt: "2026-07-01T00:00:00.000Z",
  endsAt: "2027-06-30T00:00:00.000Z",
  person: { id: PERSON, displayName: "Ana Pérez", avatarUrl: null },
});
const exampleOrganization = (status: string) => ({
  id: ORG,
  type: "CLUB",
  code: "RC-SANLORENZO",
  name: "Rotaract Club San Lorenzo",
  slug: "rc-san-lorenzo",
  status,
  parentId: "cm1district48450000000000",
  countryCode: "PY",
  region: "Central",
  city: "San Lorenzo",
  timezone: "America/Asuncion",
  logoUrl: null,
  description: null,
  updatedAt,
});

// --- E8: module installations (docs/15-modules.md) ----------------------
const INSTALLATION_STATUS = ["PENDING", "ACTIVE", "SUSPENDED", "DISABLED"];

export const INSTALLATION_VIEW_SCHEMA: JsonSchema = {
  type: "object",
  description:
    "La instalación de tu módulo en una organización, con su configuración actual.",
  required: [
    "moduleId",
    "organizationId",
    "status",
    "configuration",
    "installedAt",
  ],
  properties: {
    moduleId: { type: "string" },
    organizationId: { type: "string" },
    status: { type: "string", enum: INSTALLATION_STATUS },
    configuration: {
      type: ["object", "null"],
      description:
        "Configuración del club, ya validada contra el configurationSchema del módulo.",
    },
    installedAt: { type: "string", format: "date-time" },
    activatedAt: nullableDateTime,
    disabledAt: nullableDateTime,
  },
};

const exampleInstallation = (
  status: string,
  extra: Record<string, unknown> = {},
) => ({
  moduleId: "reuniones",
  organizationId: ORG,
  status,
  configuration: {
    emailContacto: "rc.sanlorenzo@example.org",
    votosPorClub: 1,
    avisarPorEmail: true,
    idioma: "es",
  },
  installedAt: "2026-10-02T21:10:00.000Z",
  activatedAt: null,
  disabledAt: null,
  ...extra,
});

const installationSchema = (
  extra: Record<string, unknown> = {},
  required: string[] = [],
): JsonSchema => ({
  type: "object",
  required: ["installation", ...required],
  properties: { installation: INSTALLATION_VIEW_SCHEMA, ...extra },
});

const MODULE_EVENT_NOTE =
  " Solo llega a la app dueña del módulo (la que lo registró).";
// --- end E8

const membershipSchema = (
  extra: Record<string, unknown> = {},
  required: string[] = [],
) => ({
  type: "object",
  required: ["membership", "previousStatus", ...required],
  properties: {
    membership: MEMBER_VIEW_SCHEMA,
    previousStatus: {
      type: ["string", "null"],
      enum: [...MEMBERSHIP_STATUS, null],
      description: "Estado anterior de la membresía, si se conoce.",
    },
    ...extra,
  },
});

export const EVENT_CATALOG: readonly EventDefinition[] = [
  {
    type: "membership.created.v1",
    name: "membership.created",
    version: 1,
    title: "Membresía creada",
    description:
      "Se cargó una persona en el padrón de un club. Todavía está pendiente: es socia recién cuando llega membership.activated.v1.",
    scope: "kernel.service.memberships.read",
    schema: membershipSchema(),
    example: {
      membership: exampleMember("PENDING", null),
      previousStatus: null,
    },
  },
  {
    type: "membership.activated.v1",
    name: "membership.activated",
    version: 1,
    title: "Socio activado",
    description:
      "Una membresía pasó a activa: alta de un socio nuevo, regreso de una licencia o reincorporación.",
    scope: "kernel.service.memberships.read",
    schema: membershipSchema(),
    example: {
      membership: exampleMember("ACTIVE", "2026-10-02T21:15:04.000Z"),
      previousStatus: "PENDING",
    },
  },
  {
    type: "membership.ended.v1",
    name: "membership.ended",
    version: 1,
    title: "Socio dado de baja",
    description:
      "Una membresía terminó: baja (INACTIVE), egreso (GRADUATED) o pase a otro club (TRANSFERRED). `reason` dice cuál.",
    scope: "kernel.service.memberships.read",
    schema: membershipSchema(
      {
        reason: {
          type: "string",
          enum: ["INACTIVE", "GRADUATED", "TRANSFERRED"],
        },
        endedAt: nullableDateTime,
      },
      ["reason"],
    ),
    example: {
      membership: exampleMember("INACTIVE", "2025-03-14T00:00:00.000Z"),
      previousStatus: "ACTIVE",
      reason: "INACTIVE",
      endedAt: "2026-10-02T21:15:04.000Z",
    },
  },
  {
    type: "appointment.activated.v1",
    name: "appointment.activated",
    version: 1,
    title: "Cargo asumido",
    description:
      "Una persona asumió un cargo (presidencia, secretaría, RDR...). Es el evento a usar en lugar de buscar cambios en las autoridades.",
    scope: "kernel.service.authorities.read",
    schema: {
      type: "object",
      required: ["authority"],
      properties: { authority: AUTHORITY_VIEW_SCHEMA },
    },
    example: { authority: exampleAuthority("ACTIVE") },
  },
  {
    type: "appointment.ended.v1",
    name: "appointment.ended",
    version: 1,
    title: "Cargo terminado",
    description:
      "Un cargo que estaba en ejercicio terminó: al cerrar el período, a mano, por la baja de la membresía que lo respaldaba (ENDED) o por revocación (REVOKED).",
    scope: "kernel.service.authorities.read",
    schema: {
      type: "object",
      required: ["authority"],
      properties: { authority: AUTHORITY_VIEW_SCHEMA },
    },
    example: { authority: exampleAuthority("ENDED") },
  },
  {
    type: "organization.updated.v1",
    name: "organization.updated",
    version: 1,
    title: "Club o distrito actualizado",
    description:
      "Cambiaron los datos de un club o del distrito (nombre, ciudad, logo...), o su estado (activo/inactivo) o su ubicación en el árbol.",
    scope: "kernel.service.organizations.read",
    schema: {
      type: "object",
      required: ["organization", "changedFields"],
      properties: {
        organization: ORGANIZATION_VIEW_SCHEMA,
        changedFields,
      },
    },
    example: {
      organization: exampleOrganization("ACTIVE"),
      changedFields: ["name", "city"],
    },
  },
  {
    type: "organization.archived.v1",
    name: "organization.archived",
    version: 1,
    title: "Club archivado",
    description:
      "Un club (o distrito) se archivó: dejó de existir y no admite cambios. Es definitivo.",
    scope: "kernel.service.organizations.read",
    schema: {
      type: "object",
      required: ["organization"],
      properties: { organization: ORGANIZATION_VIEW_SCHEMA },
    },
    example: { organization: exampleOrganization("ARCHIVED") },
  },
  {
    type: "person.updated.v1",
    name: "person.updated",
    version: 1,
    title: "Datos de una persona actualizados",
    description:
      "Cambiaron los datos de una persona con membresía en el alcance de la app. Los cambios de email, teléfono o fecha de nacimiento solo se informan a apps con kernel.service.persons.contact.read.",
    scope: "kernel.service.persons.read",
    schema: {
      type: "object",
      required: ["person", "changedFields"],
      properties: { person: PERSON_VIEW_SCHEMA, changedFields },
    },
    example: { person: examplePerson, changedFields: ["lastName"] },
  },
  {
    type: "period.created.v1",
    name: "period.created",
    version: 1,
    title: "Período creado",
    description: "Se creó un período institucional (por ejemplo, 2026-2027).",
    scope: "kernel.service.periods.read",
    schema: {
      type: "object",
      required: ["period"],
      properties: { period: PERIOD_VIEW_SCHEMA },
    },
    example: {
      period: {
        id: "cm1period2027club0000000",
        organizationId: ORG,
        code: "2027-2028",
        name: "Período 2027-2028",
        status: "DRAFT",
        startDate: "2027-07-01T00:00:00.000Z",
        endDate: "2028-06-30T00:00:00.000Z",
      },
    },
  },
  // --- E8: module installations, only for the module's own app.
  {
    type: "module.installed.v1",
    name: "module.installed",
    version: 1,
    title: "Módulo instalado",
    description:
      "Un club (o el distrito) instaló tu módulo. Todavía está pendiente: se usa recién cuando llega module.enabled.v1." +
      MODULE_EVENT_NOTE,
    scope: null,
    schema: installationSchema(),
    example: { installation: exampleInstallation("PENDING") },
  },
  {
    type: "module.enabled.v1",
    name: "module.enabled",
    version: 1,
    title: "Módulo activado",
    description:
      "Tu módulo quedó activo en un club (o en el distrito): desde ahora sus permisos valen ahí." +
      MODULE_EVENT_NOTE,
    scope: null,
    schema: installationSchema(),
    example: {
      installation: exampleInstallation("ACTIVE", {
        activatedAt: "2026-10-02T21:15:04.000Z",
      }),
    },
  },
  {
    type: "module.disabled.v1",
    name: "module.disabled",
    version: 1,
    title: "Módulo desactivado",
    description:
      "Un club desactivó (SUSPENDED, se puede volver a activar) o desinstaló (DISABLED) tu módulo. Sus permisos dejan de valer ahí; los datos que guarda tu app no se borran." +
      MODULE_EVENT_NOTE,
    scope: null,
    schema: installationSchema(
      { reason: { type: "string", enum: ["SUSPENDED", "DISABLED"] } },
      ["reason"],
    ),
    example: {
      installation: exampleInstallation("SUSPENDED", {
        activatedAt: "2026-10-02T21:15:04.000Z",
      }),
      reason: "SUSPENDED",
    },
  },
  {
    type: "module.configured.v1",
    name: "module.configured",
    version: 1,
    title: "Configuración del módulo actualizada",
    description:
      "Un club cambió la configuración de tu módulo. `installation.configuration` trae la configuración nueva completa." +
      MODULE_EVENT_NOTE,
    scope: null,
    schema: installationSchema(),
    example: {
      installation: exampleInstallation("ACTIVE", {
        activatedAt: "2026-10-02T21:15:04.000Z",
      }),
    },
  },
  {
    type: "ping.v1",
    name: "ping",
    version: 1,
    title: "Prueba",
    description:
      'Evento de prueba que se manda desde la consola ("Enviar prueba"). No hace falta suscribirse: llega a cualquier endpoint.',
    scope: null,
    schema: {
      type: "object",
      required: ["message", "appId", "endpointId"],
      properties: {
        message: { type: "string" },
        appId: { type: "string" },
        endpointId: { type: "string" },
      },
    },
    example: {
      message: "Hola desde Mi Rotaract",
      appId: "cm1appasistencia00000000",
      endpointId: "cm1webhookendpoint000000",
    },
  },
];

/** Sent by "Enviar prueba"; not subscribable. */
export const PING_EVENT_TYPE = "ping.v1";

export const EVENT_TYPES = EVENT_CATALOG.map((event) => event.type);

/** Types an endpoint may subscribe to. */
export const SUBSCRIBABLE_EVENT_TYPES = EVENT_TYPES.filter(
  (type) => type !== PING_EVENT_TYPE,
);

export function eventDefinition(type: string): EventDefinition | undefined {
  return EVENT_CATALOG.find((event) => event.type === type);
}

/** JSON Schema of the POSTed body (the same for every type). */
export const ENVELOPE_SCHEMA: JsonSchema = {
  type: "object",
  required: ["id", "type", "createdAt", "organizationId", "data"],
  properties: {
    id: {
      type: "string",
      pattern: "^evt_",
      description:
        "Identificador del evento. Es el mismo en cada reintento: usalo para no procesar dos veces lo mismo.",
    },
    type: { type: "string", description: "Tipo del catálogo, con su versión." },
    createdAt: {
      type: "string",
      format: "date-time",
      description: "Cuándo ocurrió el hecho en el kernel.",
    },
    organizationId: {
      type: "string",
      description:
        "Organización (dentro del alcance de la app) a la que se refiere el evento.",
    },
    data: { type: "object" },
  },
};

export type PublicEnvelope = {
  id: string;
  type: string;
  createdAt: string;
  organizationId: string;
  data: Record<string, unknown>;
};

export const EXAMPLE_EVENT_ID = "evt_cm1exampleevent000000000";
export const EXAMPLE_CREATED_AT = "2026-10-02T21:15:04.000Z";

/** The full example body of a type, exactly as it would be POSTed. */
export function exampleEnvelope(definition: EventDefinition): PublicEnvelope {
  return {
    id: EXAMPLE_EVENT_ID,
    type: definition.type,
    createdAt: EXAMPLE_CREATED_AT,
    organizationId: ORG,
    data: definition.example,
  };
}

/** Body of `GET /events/catalog`. */
export function catalogDocument() {
  return {
    version: 1,
    signature: {
      algorithm: "HMAC-SHA256",
      signedPayload: "<MiRotaract-Webhook-Timestamp>.<cuerpo crudo>",
      headers: {
        id: "MiRotaract-Webhook-Id",
        timestamp: "MiRotaract-Webhook-Timestamp",
        signature: "MiRotaract-Signature",
      },
      toleranceSec: 300,
    },
    envelope: ENVELOPE_SCHEMA,
    events: EVENT_CATALOG.map((definition) => ({
      type: definition.type,
      name: definition.name,
      version: definition.version,
      title: definition.title,
      description: definition.description,
      scope: definition.scope,
      schema: definition.schema,
      example: exampleEnvelope(definition),
    })),
  };
}
