// Human-facing names for the system catalog. Codes stay stable for code and
// integrations; these are what people read in the Web.

export const positionNames: Record<string, string> = {
  DISTRICT_RDR: "Representante Distrital (RDR)",
  DISTRICT_SECRETARY: "Secretaría distrital",
  DISTRICT_TREASURER: "Tesorería distrital",
  CLUB_PRESIDENT: "Presidencia",
  CLUB_PRESIDENT_ELECT: "Presidencia electa",
  CLUB_VICE_PRESIDENT: "Vicepresidencia",
  CLUB_SECRETARY: "Secretaría",
  CLUB_TREASURER: "Tesorería",
  CLUB_PAST_PRESIDENT: "Past presidencia",
};

export const roleNames: Record<string, string> = {
  PLATFORM_USER: "Usuario de la plataforma",
  DISTRICT_RDR: "Representante Distrital",
  DISTRICT_SECRETARY: "Secretaría distrital",
  CLUB_PRESIDENT: "Presidencia de club",
  CLUB_SECRETARY: "Secretaría de club",
  CLUB_TREASURER: "Tesorería de club",
  MEMBER: "Socio/a",
};

export const permissionNames: Record<string, string> = {
  "kernel.account.read.self": "Ver su propia cuenta",
  "kernel.account.update.self": "Editar su propia cuenta",
  "kernel.account.manage": "Suspender o reactivar cuentas",
  "kernel.person.read.self": "Ver sus propios datos personales",
  "kernel.person.update.self": "Editar sus propios datos personales",
  "kernel.person.read": "Ver datos de personas",
  "kernel.person.manage": "Crear y editar personas",
  "kernel.organization.read": "Ver clubes y distrito",
  "kernel.organization.create": "Crear clubes",
  "kernel.organization.update": "Editar datos del club",
  "kernel.organization.activate": "Activar o desactivar clubes",
  "kernel.organization.archive": "Archivar clubes",
  "kernel.organization.move": "Mover clubes de distrito",
  "kernel.membership.read": "Ver el padrón de socios",
  "kernel.membership.create": "Dar de alta socios",
  "kernel.membership.update": "Editar datos de socios",
  "kernel.membership.activate": "Activar socios",
  "kernel.membership.deactivate": "Dar de baja socios",
  "kernel.membership.transfer": "Gestionar transferencias de socios",
  "kernel.period.read": "Ver períodos",
  "kernel.period.create": "Crear períodos",
  "kernel.period.update": "Editar períodos",
  "kernel.period.activate": "Iniciar períodos",
  "kernel.period.close": "Cerrar períodos",
  "kernel.appointment.read": "Ver autoridades",
  "kernel.appointment.create": "Nominar autoridades",
  "kernel.appointment.activate": "Poner en funciones a autoridades",
  "kernel.appointment.end": "Finalizar mandatos",
  "kernel.appointment.revoke": "Revocar autoridades",
  "kernel.position.read": "Ver cargos",
  "kernel.position.create": "Crear cargos",
  "kernel.position.manage": "Editar cargos y lo que pueden hacer",
  "kernel.application.create.self": "Pedir unirse a un club",
  "kernel.application.read.self": "Ver sus propias solicitudes",
  "kernel.application.cancel.self": "Cancelar sus propias solicitudes",
  "kernel.application.review": "Aprobar o rechazar solicitudes de ingreso",
  "kernel.transfer.create.self": "Pedir su propia transferencia",
  "kernel.transfer.read.self": "Ver sus propias transferencias",
  "kernel.transfer.accept": "Aceptar transferencias entrantes",
  "kernel.transfer.confirm": "Confirmar transferencias salientes",
  "kernel.transfer.reject": "Rechazar transferencias",
  "kernel.role.read": "Ver roles",
  "kernel.role.manage": "Crear y editar roles",
  "kernel.role.assign": "Otorgar roles",
  "kernel.role.revoke": "Quitar roles",
  "kernel.module.read": "Ver módulos",
  "kernel.module.register": "Registrar módulos",
  "kernel.module.install": "Instalar módulos",
  "kernel.module.configure": "Configurar módulos",
  "kernel.module.disable": "Desactivar módulos",
  "kernel.audit.read": "Ver auditoría",
  "kernel.app.read": "Ver las apps conectadas al distrito",
  "kernel.app.manage": "Registrar y administrar apps",
  // E11: approve apps, set their limits and publish them to members.
  "kernel.app.review": "Revisar, aprobar y publicar apps",
  // --- E12 (docs/19-operations-e12.md)
  "kernel.status.manage": "Publicar incidentes y mantenimientos",
  // --- end E12
};
