#!/usr/bin/env bash
# E12.3 — hosted sandbox kernel (docs/19-operations-e12.md).
#
#   infra/sandbox/sandbox.sh init-env      # writes infra/sandbox/.env with fresh secrets
#   infra/sandbox/sandbox.sh build [--web] # builds the sandbox images
#   infra/sandbox/sandbox.sh up [--web]    # first boot: migrate, seed, golden snapshot, start
#   infra/sandbox/sandbox.sh reset         # nightly: back to the golden snapshot
#   infra/sandbox/sandbox.sh status
#   infra/sandbox/sandbox.sh down [--volumes]
#
# Nightly reset (cron, see the doc):
#   15 4 * * * /path/to/repo/infra/sandbox/sandbox.sh reset >> ~/logs/sandbox-reset.log 2>&1
#
# The reset puts every institutional record back to the seeded state, but
# KEEPS what developers registered: apps, their secrets, webhook endpoints,
# consents and the signing keys (SANDBOX_PRESERVE_TABLES). It works because
# the golden snapshot keeps ids stable across resets. Accounts created after
# the snapshot are not kept (use the test accounts), and apps owned by them
# are dropped with them.
#
# Environment: SANDBOX_ENV_FILE (default infra/sandbox/.env),
# SANDBOX_PROJECT (default mirotaract-sandbox).
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="${SANDBOX_ENV_FILE:-$HERE/.env}"
PRESERVE="${SANDBOX_PRESERVE_TABLES:-DeveloperApp DeveloperAppSecret SigningKey WebhookEndpoint OAuthConsent}"

log() { printf '%s sandbox: %s\n' "$(date +%FT%T)" "$*"; }
die() { printf '%s sandbox: ERROR %s\n' "$(date +%FT%T)" "$*" >&2; exit 1; }

compose() { docker compose --env-file "$ENV_FILE" -f "$HERE/docker-compose.yml" "$@"; }
psql_db() { compose exec -T postgres psql -U kernel -v ON_ERROR_STOP=1 "$@"; }

secret() { head -c 48 /dev/urandom | base64 | tr -d '/+=' | head -c "${1:-48}"; }

init_env() {
  [ -f "$ENV_FILE" ] && die "$ENV_FILE already exists (delete it to start over)"
  umask 077
  cat >"$ENV_FILE" <<EOF
# Sandbox secrets — generated by sandbox.sh init-env on $(date -u +%F).
# Never reuse production values: tokens must not cross environments.
SANDBOX_DB_PASSWORD=$(secret 32)
SANDBOX_JWT_SECRET=$(secret 48)
SANDBOX_SIGNING_KEY_SECRET=$(secret 48)
# Superadmin of the sandbox (admin@example.org): NOT published.
SANDBOX_ADMIN_PASSWORD=$(secret 20)
# Shared by the published test accounts (rdr@, presidencia.norte@, ...).
SANDBOX_TEST_PASSWORD=sandbox-9999
SANDBOX_ISSUER_URL=https://api.sandbox.rotaract4845.com/api/kernel/v1
SANDBOX_WEB_URL=https://sandbox.rotaract4845.com
SANDBOX_API_PORT=3011
SANDBOX_WEB_PORT=3010
EOF
  log "wrote $ENV_FILE"
}

wait_api() {
  local port id
  for _ in $(seq 1 90); do
    id="$(compose ps -q api)"
    [ -n "$id" ] && [ "$(docker inspect -f '{{.State.Health.Status}}' "$id" 2>/dev/null)" = healthy ] && return 0
    sleep 2
  done
  compose logs --tail 40 api >&2
  die "the sandbox API did not become healthy"
}

up() {
  local web=""
  [ "${1:-}" = "--web" ] && web="--profile web"
  [ -f "$ENV_FILE" ] || die "no $ENV_FILE: run sandbox.sh init-env first"
  compose up -d postgres nats
  if compose exec -T postgres test -f /snapshots/golden.dump; then
    log "golden snapshot exists: applying pending migrations only"
    compose run --rm -e SANDBOX_SETUP=migrate setup
  else
    log "first boot: migrations, base seed and the synthetic district"
    compose run --rm -e SANDBOX_SETUP=seed setup
    snapshot
  fi
  # shellcheck disable=SC2086
  compose $web up -d api ${web:+web}
  wait_api
  log "sandbox up: API on 127.0.0.1:$(grep -E "^SANDBOX_API_PORT=" "$ENV_FILE" | tail -1 | cut -d= -f2)"
}

snapshot() {
  log "taking the golden snapshot"
  compose exec -T postgres sh -c 'pg_dump -U kernel -d kernel --format=custom --no-owner -f /snapshots/golden.dump.partial && mv /snapshots/golden.dump.partial /snapshots/golden.dump'
}

reset() {
  [ -f "$ENV_FILE" ] || die "no $ENV_FILE"
  compose exec -T postgres test -f /snapshots/golden.dump || die "no golden snapshot: run sandbox.sh up first"
  log "reset: saving developer data ($PRESERVE)"
  local tables=()
  for t in $PRESERVE; do tables+=("-t" "\"$t\""); done
  compose exec -T postgres pg_dump -U kernel -d kernel --data-only --inserts \
    --on-conflict-do-nothing "${tables[@]}" -f /snapshots/preserve.sql
  log "reset: stopping the API and restoring the golden snapshot"
  compose stop api
  psql_db -d postgres -c "SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE datname = 'kernel' AND pid <> pg_backend_pid()" >/dev/null
  psql_db -d postgres -c 'DROP DATABASE kernel' -c 'CREATE DATABASE kernel' >/dev/null
  compose exec -T postgres pg_restore -U kernel -d kernel --no-owner --exit-on-error /snapshots/golden.dump
  log "reset: migrations newer than the snapshot"
  compose run --rm -e SANDBOX_SETUP=migrate setup >/dev/null
  log "reset: putting developer data back (rows whose owner no longer exists are skipped)"
  # No ON_ERROR_STOP: one orphan row must not drop the others.
  compose exec -T postgres psql -U kernel -d kernel -q -f /snapshots/preserve.sql 2>&1 |
    grep -c ERROR | xargs -I{} echo "  {} rows skipped" || true
  compose start api
  wait_api
  log "reset done"
}

case "${1:-}" in
  init-env) init_env ;;
  build)
    shift
    compose build setup
    [ "${1:-}" = "--web" ] && compose --profile web build web
    ;;
  up) shift; up "${1:-}" ;;
  reset) reset ;;
  snapshot) snapshot ;;
  status) compose ps ;;
  down) shift; compose --profile web --profile setup down ${1:+"$1"} ;;
  *) sed -n '2,25p' "$0"; exit 2 ;;
esac
