import iaJson from "@/generated/ia.json";

/** Generated by scripts/prepare-content.mjs (prepareIa) from packages/ai-skills. */
export type Idea = {
  id: string;
  title: string;
  summary: string;
  template: "next" | "fastapi";
  scope: "club" | "distrito";
  idea: string;
  users: string;
  data: string;
  guide: string | null;
};

export type IaContent = {
  master: string;
  planning: string;
  ideas: Idea[];
  bundle: {
    version: string;
    fingerprint: string;
    status: "preliminary" | "evaluated";
    note: string;
    sha256: string;
    skills: Array<{ name: string; title: string }>;
    files: Array<{ target: string; path: string; url: string }>;
  };
};

export const ia = iaJson as IaContent;
